/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const useDialog: (typeof import('@zebra-ui/uniapp'))['useDialog']
  const useNotify: (typeof import('@zebra-ui/uniapp'))['useNotify']
  const useToast: (typeof import('@zebra-ui/uniapp'))['useToast']
}
