export const BORDER = 'z-hairline'
export const BORDER_TOP = `${BORDER}--top`
export const BORDER_LEFT = `${BORDER}--left`
export const BORDER_RIGHT = `${BORDER}--right`
export const BORDER_BOTTOM = `${BORDER}--bottom`
export const BORDER_SURROUND = `${BORDER}--surround`
export const BORDER_ORGIN = `${BORDER}--orgin`
export const BORDER_TOP_BOTTOM = `${BORDER}--top-bottom`
export const BORDER_UNSET_TOP_BOTTOM = `${BORDER}-unset--top-bottom`
export const HAPTICS_FEEDBACK = 'z-haptics-feedback'
export const FORM_KEY: any = 'z-form'
export const LONG_PRESS_START_TIME = 500
export const TAP_OFFSET = 5
