name: Upload Files to Server

on:
  push:
    branches:
      - master
    paths:
      - docs/zebra-ui-docs/**
      - demos/demo-cli/**

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build H5 for demo-cli
        run: pnpm run build:h5
        working-directory: demos/demo-cli

      - name: Copy H5 build output
        run: cp -r demos/demo-cli/dist/build/h5 docs/zebra-ui-docs/public

      - name: Build Site
        run: pnpm run build
        working-directory: docs/zebra-ui-docs

      - name: Upload File via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'docs/zebra-ui-docs/.output,docs/zebra-ui-docs/Dockerfile'
          target: '/www/wwwroot/zebraui-docs/'
          rm: true

      - name: ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          last_ssh: |
            cd /www/wwwroot/zebraui-docs/docs/zebra-ui-docs
            docker stop zebra-ui-docs-docker
            docker rm -f zebra-ui-docs-docker
            docker build -t zebra-ui-docs-docker .
            docker run --name zebra-ui-docs-docker -d -p 3000:3000 zebra-ui-docs-docker
