name: DOCS to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/zebra-ui-docs/**
      - demos/demo-cli/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build Nuxt project
        run: npx nuxt build --preset github_pages
        working-directory: docs/zebra-ui-docs

      - name: Build H5 for demo-cli
        run: pnpm run build:h5
        working-directory: demos/demo-cli

      - name: Copy H5 build output
        run: cp -r demos/demo-cli/dist/build/h5 docs/zebra-ui-docs/.output/public

      - name: Deploy for Github 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: docs/zebra-ui-docs/.output/public
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true
